version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "monthly"
  cooldown:
    default-days: 4
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  cooldown:
    default-days: 4
