name: CI

on:
  push:
    branches-ignore:
      - main
  schedule:
    - cron: '30 17 15 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache Maven packages
      uses: actions/cache@v2.1.5
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      env:
        REVISION: ${{ github.sha }}
      run: |
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          verify
        mkdir target/artifacts
        cp target/website-janitor-* target/artifacts
    - uses: actions/upload-artifact@v2.2.2
      with:
        name: website-janitor-${{ github.job }}-${{ github.sha }}
        path: target/artifacts
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Cache Maven packages
      uses: actions/cache@v2.1.5
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REVISION: ${{ github.sha }}
      run: |
        ./mvnw \
          --batch-mode \
          --settings ./.github/github-packages-settings.xml \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          -DaltDeploymentRepository="github::default::https://maven.pkg.github.com/${GITHUB_REPOSITORY}" \
          deploy
